{% set version = "0.2.0" %}

package:
  name: soapysdr-module-netsdr
  version: {{ version }}

source:
  url: https://github.com/pothosware/SoapyNetSDR/archive/soapy-netsdr-{{ version }}.tar.gz
  sha256: 229b727228871220784faa21495fdb366ca708bc5c4bc4dcb5130ea640e13a82
  patches:
    - 0001-Fix-segfault-caused-by-dereferencing-NULL-pointer-in.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - soapysdr

test:
  commands:
    # verify that libraries get installed
    - test -f $PREFIX/lib/SoapySDR/modules{{ soapysdr }}/libnetSDRSupport.so  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\SoapySDR\\modules{{ soapysdr }}\\netSDRSupport.dll exit 1  # [win]

    # show info to see if module is detected
    - SoapySDRUtil --info
    - SoapySDRUtil --info | grep netSDRSupport  # [not win]
    - SoapySDRUtil --info | findstr /l netSDRSupport  # [win]

about:
  home: https://github.com/pothosware/SoapyNetSDR/wiki
  license: MIT
  license_file: License.txt
  summary: 'SoapySDR Support Module for NetSDR protocol'
  description: >
    The Soapy NetSDR project provides a plugin module to use the NetSDR devices
    within the SoapySDR API and software that supports SoapySDR.
  doc_url: https://github.com/pothosware/SoapyNetSDR/wiki
  dev_url: https://github.com/pothosware/SoapyNetSDR

extra:
  recipe-maintainers:
    - ryanvolz
